### ISSUE TITLE
Install URIgen server for generating new URIs

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#14]
https://github.com/simonjupp/urigen

Should be able to download a simple WAR file to run server. 

This should become part of the pipeline for rapidly adding new individuals to the vfb_neo4J_kb.  We need this reasonably soon so that we can use it for a pipeline for generating new individuals and annotations on demand for the adult brain EM project.

CC @jefferis @mmc46

**Comment by Robbie1977** [comment]
FYI not deploying with tomcat 6. @dosumis do you know the minimum requirements?

**Comment by dosumis** [comment]
war file worked for me last time I tried it.  IIRC I was using Tomcat but this was about 4 years ago so would have been an older version.

@simonjupp Any suggestions?

**Comment by simonjupp** [comment]
Should just require tomcat. What errors are you seeing?

**Comment by Robbie1977** [comment]
```
2016-11-30 15:45:29,425 INFO [http-8080-2] context.ContextLoader (ContextLoader.java:187) - Root WebApplicationContext: initialization started
2016-11-30 15:45:29,463 INFO [http-8080-2] support.AbstractApplicationContext (AbstractApplicationContext.java:456) - Refreshing Root WebApplicationContext: startup date [Wed Nov 30 15:45:29 GMT 2016]; root of context hierarchy
2016-11-30 15:45:29,515 INFO [http-8080-2] xml.XmlBeanDefinitionReader (XmlBeanDefinitionReader.java:315) - Loading XML bean definitions from ServletContext resource [/WEB-INF/urigen-dao.xml]
2016-11-30 15:45:29,550 INFO [http-8080-2] xml.XmlBeanDefinitionReader (XmlBeanDefinitionReader.java:315) - Loading XML bean definitions from ServletContext resource [/WEB-INF/urigen-service.xml]
2016-11-30 15:45:29,670 INFO [http-8080-2] support.PropertiesLoaderSupport (PropertiesLoaderSupport.java:177) - Loading properties file from class path resource [urigen.properties]
2016-11-30 15:45:29,674 INFO [http-8080-2] support.DefaultSingletonBeanRegistry (DefaultSingletonBeanRegistry.java:422) - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@6c023b5e: defining beans [hsqlJdbcTemplate,hsqlDatasource,hsqlInitializer,userDAO,preferenceDAO,entityDAO,ontologyDAO,org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0,urigenManager,userService,preferenceService,uriCreationService]; root of factory hierarchy
2016-11-30 15:45:29,675 ERROR [http-8080-2] context.ContextLoader (ContextLoader.java:220) - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'hsqlDatasource' defined in ServletContext resource [/WEB-INF/urigen-dao.xml]: Could not resolve placeholder 'urigen.home.directory'
at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:272)
at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:75)
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:663)
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:638)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:407)
at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4210)
at org.apache.catalina.core.StandardContext.start(StandardContext.java:4709)
at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1276)
at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:625)
at org.apache.catalina.manager.HTMLManagerServlet.doGet(HTMLManagerServlet.java:136)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:563)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)
at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
at java.lang.Thread.run(Thread.java:745)

Nov 30, 2016 3:45:29 PM org.apache.catalina.core.StandardContext start
SEVERE: Error listenerStart

Nov 30, 2016 3:45:29 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [/urigen] startup failed due to previous errors
```

**Comment by Robbie1977** [comment]
Where should urigen.home.directory be set?

**Comment by Robbie1977** [comment]
Have moved the home dir as the tomcat user has no home dir and is now working here: http://blanik.inf.ed.ac.uk:8080/urigen/ (inside VPN)
