### ISSUE TITLE
Base10 not Base36 used in KB_tools.py

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#195]
```
python3 /opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/import_pub_data.py http://192.168.114.2:7474 neo4j vfb
Traceback (most recent call last):
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/import_pub_data.py", line 17, in <module>
    pm = pubMover(base_uri, usr, pwd)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/fb_tools.py", line 80, in __init__
    self._init(endpoint, usr, pwd)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/fb_tools.py", line 86, in _init
    self.pattern_writer = KB_pattern_writer(endpoint, usr, pwd)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/KB_tools.py", line 703, in __init__
    self.iri_gen = iri_generator(endpoint, usr, pwd)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/KB_tools.py", line 142, in __init__
    base=base)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/KB_tools.py", line 162, in _configure
    self.lookup = [int(x.split('_')[1]) for x in self.id_name.keys()]
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/KB_tools.py", line 162, in <listcomp>
    self.lookup = [int(x.split('_')[1]) for x in self.id_name.keys()]
ValueError: invalid literal for int() with base 10: 'jrch0a01'
ValueError: invalid literal for int() with base 10: 'jrch0a01'
-e travis_fold:end:import_pub_data
```

**Comment by Robbie1977** [comment]
Failed build not loading Base36 https://hub.docker.com/repository/registry-1.docker.io/rcourt/python3.7/builds/60c2b33b-793d-4638-b82f-014c752e40e4

**Comment by dosumis** [comment]
Hmmm - I guess either we switch or we don't.  Hard to support both on same DB.

**Comment by Robbie1977** [comment]
Should have resolved on that odd branch else I'll switch the whole thing to the same standard container
