### ISSUE TITLE
KB2Prod

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#32]
Most information should move between KB and Prod via OWL, but some will have to be moved directly.

1. All nodes not marked as :Class or :Individual or :Property

```cql
MATCH (n) 
WHERE not('Class' IN labels(n)) 
AND not('Individual' IN labels(n)) 
AND not('Property' IN labels(n))  RETURN 
labels(n) AS labels , properties(n) as properties; 
```

=>
REST QUERY JSON:

```python
[{'columns': ['labels', 'properties'],
  'data': [{'meta': [None, None, None, None],
    'row': [['data_source'],
     {'dataset_link': 'http://flybase.org/reports/FBrf0221412.html',
      'dataset_spec_text': 'This clone was generated by FLP-out MARCM at larval hatching. It therefore does not include embryonic born neurons.',
      'name': 'Yu2013'}]},
```

2. All edges not marked as :Related, :INSTANCEOF, :SUBCLASSOF*

\* So far we don't have any of these in KB

```cql
MATCH (n)-[r]->(m) 
WHERE not(type(r) IN ['INSTANCEOF', 'Related']) 
RETURN n.IRI AS subject, type(r) AS reltype, 
properties(r) AS relprops, m.IRI AS object 
LIMIT 3
```
=>
REST QUERY JSON:

```python
[{'columns': ['subject', 'reltype', 'relprops', 'object'],
  'data': [{'meta': [None, None, None, None],
    'row': ['http://virtualflybrain.org/reports/VFB_00024231',
     'has_source',
     {'id_in_source': 'None'},
     None]},
   {'meta': [None, None, None, None],
    'row': ['http://virtualflybrain.org/reports/VFB_00024233',
     'has_source',
     {'id_in_source': 'None'},
     None]}]}]
```

We need a standard script that unrolls these and re-rolls them for prod.

In the current scheme, channel individuals are not translated to OWL.  
TBD: Is it easier to transfer these directly, or to extend the current OWL rolling scripts?  

Note: New OWL gen via scala will take channels by default.

**Comment by dosumis** [comment]
Draft script: 

https://github.com/VirtualFlyBrain/VFB_neo4j/commit/076436655ef8ebdf46950beba0d2087626221253

**Comment by dosumis** [comment]
What's needed for KB2Prod script:

IRI (in KB) -> iri
in_register_with -> Related { ..}  - I'd like to treat this as OWL.

all non-owl nodes to get an iri
data_source = VFB URL   (# note - Would be better named DataSet)
Site = homepage
License = CC URL
Pub = ??  Bit difficult as not all pubs have same identifier available.  

Could set ranking:
Use PMID if available
The FBrf
Then ISBN
...

@Robbie1977

**Comment by dosumis** [comment]
Scripts now working and tested locally.

**Comment by Robbie1977** [comment]
Error on current version:
```Processing chunk of 62 of 61 starting with: b'MATCH (s:VFB:Individual { iri : \'http://virtualflybrain.org/reports/VFBc_00000521\'}),  (o:VFB:Individual { iri :\'http://virtualflybrain.org/reports/VFBc_00030618\'}) MERGE (s)-[r:Related ]->(o) SET r = { voxel_overlap_left : 199 , label : "overlaps" , iri : "http://purl.obolibrary.org/obo/RO_0002131" , voxel_overlap_right : 193 , short_form : "RO_0002131" }'
Processing took 0 seconds for 95 statements
Estimated time to completion: -1 day, 23:59:59.795546.
Traceback (most recent call last):
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo2neo/KB2Prod.py", line 72, in <module>
    test_mode=False)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo4j_tools.py", line 233, in move_edges
    edges = results_2_dict_list(results)
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo4j_tools.py", line 141, in results_2_dict_list
    for n in results:
TypeError: 'bool' object is not iterable```

**Comment by dosumis** [comment]
AFAIK this is all fixed.  Any bugs found in this should be new ticket.
