### ISSUE TITLE
Cypher query for pulling full meta data from short_form

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#8]
I need the cypher query to pull back (everything we currently can) metadata for an object, ideally a single query or class/individual specific one.

**Comment by dosumis** [comment]
This will work for classes once we have the build in place:

     query: anatomy_term_full
      description: "Full information on an anatomy term, for use in term info pages."
      subqueries:
         - cypher: "MATCH (n:VFB:Class { short_form: '%s' } ) 
         RETURN n.label, n.short_form, n.description, n.comment"
         - cypher: "'MATCH (n:VFB:Class { short_form: '%s' } )
         -[r:SUBCLASSOF|Related|has_reference]->(sc) 
         RETURN r, sc.label, sc.miniref, sc.short_form, sc.FlyBase'"
         - cypher: "MATCH (n:VFB:Class { short_form: '%s' } )
         <-[:SUBCLASSOF*]-()<-[:INSTANCEOF]-(i) 
         RETURN i.short_form, i.label LIMIT 5"
  
* First query finds basic metadata (name, def, comment) 
* Second query finds parent classes, related classes, synonyms and definitions.  Requires a small amount of post processing.  Can easily be extended to pull PMIDS, DOIS etc (n.PMID, n.DOI...)
* Third query finds 5 individual members of the class (bit slower without a limit set).  Elk Query can be used to => accurate number quickly.
TBA: Extension to query 3 to find image IDs.

Here's the equivalent for individuals:

      query: individual_term_full
      description: "Full information on an anatomical individual term, 
      for use in term info pages."
      subqueries:
         - cypher: "MATCH (n:VFB:Individual { short_form: '%s' } ) 
         RETURN n.label, n.short_form, n.description, n.comment"
         - cypher: "'MATCH (n:VFB:Class { short_form: '%s' } )
         -[r:INSTANCEOF|Related|has_reference]->(sc) 
         RETURN r, sc.label, sc.short_form, sc.FlyBase'"
         - cypher: # TBA - cypher query for image IDs

**Comment by Robbie1977** [comment]
@dosumis are you creating 'comment' as currently it's 'annotation-comment' which is a pain as I think has to be escaped as n.["annotation-comment"]?

**Comment by dosumis** [comment]
That's correct (attribute wrong in cypher above). I'm afraid all obo-specific attributes have this problem in the OLS translation.  I've been using backticks to escape these attribute names.

**Comment by Robbie1977** [comment]
can you give an example with backticks as I couldn't get the syntax right?

**Comment by dosumis** [comment]
MATCH (n) WHERE has(n.`annotation-comment`) RETURN n.`annotation-comment` limit 5

**Comment by Robbie1977** [comment]
Trying to put together a test set for how we create a 'variable' for a given ID:

```
MATCH (n:VFB { short_form: '$ID' } ) RETURN n.label, n.short_form, n.description, n.`annotation-comment`, labels(n)  LIMIT 1;
```
Gives us the main items and importantly tells us the labels which specify individual/class

From there we need to 

Pull the references:
```
MATCH (n:VFB:Class { short_form: '%s' } )
     -[r:SUBCLASSOF|Related|has_reference]->(sc) 
     RETURN r, sc.label, sc.miniref, sc.short_form, sc.FlyBase
```
which we currently don't have in our Neo4J. @dosumis can we work on adding this if you've perfected the addon code?

Associated individuals:
```
MATCH (n:VFB:Class { short_form: 'FBbt_00005106' } )<-[:SUBCLASSOF*]-()<-[:INSTANCEOF]-(i) RETURN i.short_form, i.label LIMIT 5
```


For Individuals just need the references and filenames - @dosumis how did you get on with adding instance for 'channels' with file refs?

@dosumis is there any reason we can't just have a universal reference query (for both class/individual):
```
MATCH (n:VFB { short_form: '%s' } )
     -[r:SUBCLASSOF|INSTANCEOF|Related|has_reference]->(sc) 
     RETURN r, sc.label, sc.miniref, sc.short_form, sc.FlyBase
```

**Comment by dosumis** [comment]
On 21 Mar 2016, at 17:28, Rob Court <notifications@github.com> wrote:

> Trying to put together a test set for how we create a 'variable' for a given ID:
> 
> MATCH (n:VFB { short_form: '$ID' } ) RETURN n.label, n.short_form, n.description, n.`annotation-comment`, labels(n)  LIMIT 1;
> Gives us the main items and importantly tells us the labels which specify individual/class
> 
> 
Once the denormalisation code has been run, labels also => crude typing: clone, neuron, tract etc.
> From there we need to
> 
> Pull the references:
> 
> MATCH (n:VFB:Class { short_form: '%s' } )
>      -[r:SUBCLASSOF|Related|has_reference]->(sc) 
>      RETURN r, sc.label, sc.miniref, sc.short_form, sc.FlyBase

This pulls superclasses, relationships,  references and synonyms (& refs on synonyms)
> which we currently don't have in our Neo4J. @dosumis can we work on adding this if you've perfected the addon code?
> 

It's been ready for about a month.  Needs latest version of vfb.owl to work.

> Associated individuals:
> 
> MATCH (n:VFB:Class { short_form: 'FBbt_00005106' } )<-[:SUBCLASSOF*]-()<-[:INSTANCEOF]-(i) RETURN i.short_form, i.label LIMIT 5
> For Individuals just need the references and filenames - @dosumis how did you get on with adding instance for 'channels' with file refs?
> 
Partially done.  Some work on LMB DB needed.  Very little time to work on this until week starting 4th April (at a meeting in Amsterdam for the rest of this week, then on holiday).
> @dosumis is there any reason we can't just have a universal reference query (for both class/individual):
> 
> MATCH (n:VFB { short_form: '%s' } )
>      -[r:SUBCLASSOF|INSTANCEOF|Related|has_reference]->(sc) 
>      RETURN r, sc.label, sc.miniref, sc.short_form, sc.FlyBase
Need to be clearer what you want this for.  From an individual, it will give you refs and synonyms (as much as we have them).  From a class it will => direct instances only  (unlike the 'associated individuals' query above - which will give all instances).

**Comment by dosumis** [comment]
Order of running for loading scripts is important:

1. uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py  (sets essential U Constraints) 
2. https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/code/owl2neo/add_anonymous_types.py
3. https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/code/owl2neo/add_refs_for_anat.py
4. uk/ac/ebi/vfb/neo4j/flybase2neo/import_pub_data.py
5. uk/ac/ebi/vfb/neo4j/neo2neo/make_named_edges.py

The two scripts on VFB_owl are Jython and require
Can you aet up chained Jenkins jobs to run these?

**Comment by dosumis** [comment]
Quick and dirty script for pulling triples directly from LMB DB (requires tunnel): 

https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/code/owl2neo/add_facts_from_lmb.py

Note - it currently doesn't pull any typing information on individuals, just bare triples.  Probably needs at least basic typing to image & channel to be useful - although it is possible to tell a type from its ID (VFBi for images, VFBc for channels).

**Comment by Robbie1977** [comment]
For 'python3 uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py neo4J_API_URI usr pwd' is this expected:
```
/opt/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/tools.py:77: UserWarning: {'code': 'Neo.DatabaseError.Schema.ConstraintCreationFailure', 'stackTrace': "org.neo4j.kernel.impl.query.QueryExecutionKernelException: Unable to create CONSTRAINT ON ( vfb:VFB ) ASSERT vfb.short_form IS UNIQUE:\nMultiple nodes with label `VFB` have property `short_form` = 'SO_0000704':\n  node(1448)\n  node(11848)\n\tat org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:66)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:328)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:147)\n\tat org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: org.neo4j.cypher.CypherExecutionException: Unable to create CONSTRAINT ON ( vfb:VFB ) ASSERT vfb.short_form IS UNIQUE:\nMultiple nodes with label `VFB` have property `short_form` = 'SO_0000704':\n  node(1448)\n  node(11848)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContextFor2_3$$translateException(ExceptionTranslatingQueryContextFor2_3.scala:199)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.createUniqueConstraint(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compiler.v2_3.spi.UpdateCountingQueryContext.createUniqueConstraint(UpdateCountingQueryContext.scala:104)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.ConstraintOperationPipe.internalCreateResults(ConstraintOperationPipe.scala:37)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.Pipe$class.createResults(Pipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.ConstraintOperationPipe.createResults(ConstraintOperationPipe.scala:30)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:93)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:63)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:228)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:212)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.ExecutionPlanBuilder$$anon$2.run(ExecutionPlanBuilder.scala:170)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_3$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_3.scala:200)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_3$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_3.scala:200)\n\tat org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_3$.runSafely(CompatibilityFor2_3.scala:116)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_3$ExecutionPlanWrapper.run(CompatibilityFor2_3.scala:199)\n\tat org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:27)\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:120)\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:114)\n\tat org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:62)\n\t... 33 more\nCaused by: org.neo4j.kernel.api.exceptions.schema.CreateConstraintFailureException: Unable to create constraint CONSTRAINT ON ( n:label[4] ) ASSERT n.property[2] IS UNIQUE: Existing data does not satisfy CONSTRAINT ON ( n:label[4] ) ASSERT n.property[2] IS UNIQUE.\n\tat org.neo4j.kernel.impl.api.StateHandlingStatementOperations.uniquePropertyConstraintCreate(StateHandlingStatementOperations.java:535)\n\tat org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.uniquePropertyConstraintCreate(ConstraintEnforcingEntityOperations.java:532)\n\tat org.neo4j.kernel.impl.api.DataIntegrityValidatingStatementOperations.uniquePropertyConstraintCreate(DataIntegrityValidatingStatementOperations.java:161)\n\tat org.neo4j.kernel.impl.api.LockingStatementOperations.uniquePropertyConstraintCreate(LockingStatementOperations.java:318)\n\tat org.neo4j.kernel.impl.api.OperationsFacade.uniquePropertyConstraintCreate(OperationsFacade.java:957)\n\tat org.neo4j.cypher.internal.spi.v2_3.TransactionBoundQueryContext.createUniqueConstraint(TransactionBoundQueryContext.scala:437)\n\tat org.neo4j.cypher.internal.compiler.v2_3.spi.DelegatingQueryContext.createUniqueConstraint(DelegatingQueryContext.scala:101)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContextFor2_3$$super$createUniqueConstraint(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3$$anonfun$createUniqueConstraint$1.apply(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3$$anonfun$createUniqueConstraint$1.apply(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContextFor2_3$$translateException(ExceptionTranslatingQueryContextFor2_3.scala:197)\n\t... 51 more\nCaused by: org.neo4j.kernel.api.exceptions.schema.UniquenessConstraintVerificationFailedKernelException: Existing data does not satisfy CONSTRAINT ON ( n:label[4] ) ASSERT n.property[2] IS UNIQUE.\n\tat org.neo4j.kernel.impl.api.state.ConstraintIndexCreator.awaitIndexPopulation(ConstraintIndexCreator.java:130)\n\tat org.neo4j.kernel.impl.api.state.ConstraintIndexCreator.createUniquenessConstraintIndex(ConstraintIndexCreator.java:70)\n\tat org.neo4j.kernel.impl.api.StateHandlingStatementOperations.uniquePropertyConstraintCreate(StateHandlingStatementOperations.java:526)\n\t... 61 more\n", 'message': "Unable to create CONSTRAINT ON ( vfb:VFB ) ASSERT vfb.short_form IS UNIQUE:\nMultiple nodes with label `VFB` have property `short_form` = 'SO_0000704':\n  node(1448)\n  node(11848)"}
  warnings.warn(str(e))
```

**Comment by dosumis** [comment]
Uniqueness constraint violation - from an old version of the individuals file (has 2 versions of SO_0000704).  Try loading the file generated by the owl individuals build job.

(Note to self: should fail, rather than warn after first test).

**Comment by Robbie1977** [comment]
next issue same script (neo4j loaded with http://purl.obolibrary.org/obo/fbbt/vfb/fbbt_vfb_ind.owl):
```
/opt/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/tools.py:77: UserWarning: {'message': "Unable to create CONSTRAINT ON ( vfb:VFB ) ASSERT vfb.short_form IS UNIQUE:\nMultiple nodes with label `VFB` have property `short_form` = 'Thing':\n  node(3907)\n  node(55593)", 'code': 'Neo.DatabaseError.Schema.ConstraintCreationFailure', 'stackTrace': "org.neo4j.kernel.impl.query.QueryExecutionKernelException: Unable to create CONSTRAINT ON ( vfb:VFB ) ASSERT vfb.short_form IS UNIQUE:\nMultiple nodes with label `VFB` have property `short_form` = 'Thing':\n  node(3907)\n  node(55593)\n\tat org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:66)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:328)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:147)\n\tat org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: org.neo4j.cypher.CypherExecutionException: Unable to create CONSTRAINT ON ( vfb:VFB ) ASSERT vfb.short_form IS UNIQUE:\nMultiple nodes with label `VFB` have property `short_form` = 'Thing':\n  node(3907)\n  node(55593)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContextFor2_3$$translateException(ExceptionTranslatingQueryContextFor2_3.scala:199)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.createUniqueConstraint(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compiler.v2_3.spi.UpdateCountingQueryContext.createUniqueConstraint(UpdateCountingQueryContext.scala:104)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.ConstraintOperationPipe.internalCreateResults(ConstraintOperationPipe.scala:37)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.Pipe$class.createResults(Pipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.ConstraintOperationPipe.createResults(ConstraintOperationPipe.scala:30)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:93)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:63)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:228)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:212)\n\tat org.neo4j.cypher.internal.compiler.v2_3.executionplan.ExecutionPlanBuilder$$anon$2.run(ExecutionPlanBuilder.scala:170)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_3$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_3.scala:200)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_3$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_3.scala:200)\n\tat org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_3$.runSafely(CompatibilityFor2_3.scala:116)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_3$ExecutionPlanWrapper.run(CompatibilityFor2_3.scala:199)\n\tat org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:27)\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:120)\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:114)\n\tat org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:62)\n\t... 33 more\nCaused by: org.neo4j.kernel.api.exceptions.schema.CreateConstraintFailureException: Unable to create constraint CONSTRAINT ON ( n:label[11] ) ASSERT n.property[2] IS UNIQUE: Existing data does not satisfy CONSTRAINT ON ( n:label[11] ) ASSERT n.property[2] IS UNIQUE.\n\tat org.neo4j.kernel.impl.api.StateHandlingStatementOperations.uniquePropertyConstraintCreate(StateHandlingStatementOperations.java:535)\n\tat org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.uniquePropertyConstraintCreate(ConstraintEnforcingEntityOperations.java:532)\n\tat org.neo4j.kernel.impl.api.DataIntegrityValidatingStatementOperations.uniquePropertyConstraintCreate(DataIntegrityValidatingStatementOperations.java:161)\n\tat org.neo4j.kernel.impl.api.LockingStatementOperations.uniquePropertyConstraintCreate(LockingStatementOperations.java:318)\n\tat org.neo4j.kernel.impl.api.OperationsFacade.uniquePropertyConstraintCreate(OperationsFacade.java:957)\n\tat org.neo4j.cypher.internal.spi.v2_3.TransactionBoundQueryContext.createUniqueConstraint(TransactionBoundQueryContext.scala:437)\n\tat org.neo4j.cypher.internal.compiler.v2_3.spi.DelegatingQueryContext.createUniqueConstraint(DelegatingQueryContext.scala:101)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContextFor2_3$$super$createUniqueConstraint(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3$$anonfun$createUniqueConstraint$1.apply(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3$$anonfun$createUniqueConstraint$1.apply(ExceptionTranslatingQueryContextFor2_3.scala:113)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor2_3.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContextFor2_3$$translateException(ExceptionTranslatingQueryContextFor2_3.scala:197)\n\t... 51 more\nCaused by: org.neo4j.kernel.api.exceptions.schema.UniquenessConstraintVerificationFailedKernelException: Existing data does not satisfy CONSTRAINT ON ( n:label[11] ) ASSERT n.property[2] IS UNIQUE.\n\tat org.neo4j.kernel.impl.api.state.ConstraintIndexCreator.awaitIndexPopulation(ConstraintIndexCreator.java:130)\n\tat org.neo4j.kernel.impl.api.state.ConstraintIndexCreator.createUniquenessConstraintIndex(ConstraintIndexCreator.java:70)\n\tat org.neo4j.kernel.impl.api.StateHandlingStatementOperations.uniquePropertyConstraintCreate(StateHandlingStatementOperations.java:526)\n\t... 61 more\n"}
  warnings.warn(str(e))
```

**Comment by Robbie1977** [comment]
Swapped to vfb.owl and have got passed the first script.

The first jython one is now causing an issue: 
@dosumis which version of the owlapi are you using and where should I get it from?

**Comment by dosumis** [comment]
All calls to the OWL-API are through OWLtools/Brain. We've already worked on generating compatible  builds for these (ones that use the same OWL-API version) for building the individuals file. These jobs should have exactly the same setup as that one.

**Comment by Robbie1977** [comment]
@dosumis where is neo4j_tools as seems to have been deleted?

**Comment by Robbie1977** [comment]
If I recreate from the deleted version I get stuck at:
```
Traceback (most recent call last):
  File "/opt/VFB_owl/src/code/owl2neo/add_anonymous_types.py", line 32, in <module>
    types = vom.typeAxioms2pdm(sfid = i)
  File "/opt/VFB_owl/src/code/mod/owl2pdm_tools.py", line 154, in typeAxioms2pdm
    types = self.get_types_for_ind(iri_string = iri_string, sfid = sfid)
  File "/opt/VFB_owl/src/code/mod/owl2pdm_tools.py", line 115, in get_types_for_ind
    i = self.bi_sfp.getEntity(sfid)
TypeError: getEntity(): 1st arg can't be coerced to String
```

**Comment by dosumis** [comment]
My bad.  Fixing now - but need to clean up my local repo first.  Will fix when I get out of meeting (in about 30')

**Comment by dosumis** [comment]
OK.  Should now be fixed.

BTW - did you do something with repo setup?  Pull => lots of mode changes on files

**Comment by Robbie1977** [comment]
still getting:
```
Traceback (most recent call last):
  File "/opt/VFB_owl/src/code/owl2neo/add_anonymous_types.py", line 32, in <module>
    types = vom.typeAxioms2pdm(sfid = i)
  File "/opt/VFB_owl/src/code/mod/owl2pdm_tools.py", line 177, in typeAxioms2pdm
    types = self.get_types_for_ind(iri_string = iri_string, sfid = sfid)
  File "/opt/VFB_owl/src/code/mod/owl2pdm_tools.py", line 138, in get_types_for_ind
    i = self.bi_sfp.getEntity(sfid)
TypeError: getEntity(): 1st arg can't be coerced to String
```

**Comment by Robbie1977** [comment]
I'm assuming when you say vfb.owl you mean https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/vfb.owl
